---
title: "2018_AAAS-PD-notes"
author: "Reid Otsuji"
date: "6/13/2018"
output: html_document
---

# 2018 AAAS-PD, Cal Poly Pomona
# Symposium information 

Library Science is a “discipline with primarily a practical aim" (Hjørland, 1999, p. 512). This does not transmute the fact that the field is grounded in fundamental theory and research. Practice-based research can relate to specific approaches to concrete problems at individual institutions, while theoretical research is more general in nature, can be applied to multiple library environments, and is not necessarily based on concrete practices (Audunson, 2007; Chow, Shaw, Gwynn, Martensen, & Howard, 2011; Hjørland, 1999). These methods of library research complement each other and work in tandem to enrich the discipline as a whole.   

This symposium will focus on both the theory and practice of librarianship in academia, which invites an all-inclusive consideration of libraries and librarians in the learning environment. From case studies involving practice at specific institutions to abstract investigations addressing aspects of the discipline at large, this symposium intends to foster a dialogue on a variety of library issues, such as instruction, reference, collection development, digitization, scholarly communication, and library leadership and management.    

[Abstracts](http://associations.sou.edu/aaaspd/2018POMONA/SympAbstracts2018/12.pdf)   


---


### Failure or Perseverance? A Case Study of a Legislative Initiative by the Utah Academic Library Consortium (UALC), PETER L. KRAUS (J. Willard Marriott Library, University of Utah, 295 South 1500 East, Salt Lake City, UT 84112; peter.kraus@utah.edu).     




---


### Mentoring the Future STEM Librarian, PERLA HERNANDEZ* and ZOE PETTWAY UNNO* (USC Libraries, Science and Engineering Library, University of Southern California, Los Angeles, CA 90089-0481; zunno@usc.edu, perlah@usc.edu).   

shift in workforce trends   
librairans reitred, but could not fill positions   

recommended new librarians become stem librairans via challenge grant -   
pilot money to tarin librairans through 15 week internships   

students applied, and had to show interest   

Host location SJSU portal 

Paid internship

internship required learning outcomes -   
e.g. reference work;  working with databases;  adapting library services for students e.g. creating vid tutorials chem, libguies general sci , displays for outreach; research process - helping patrons conduct effective research;   professional development - attending conferences    


Outcomes:  
introduce lis student to academic librarianship    

promoted internship through list serves    




---


### Succession Planning in Academic Libraries with Flat Organizational Structures, CRYSTAL GOLDMAN (Geisel Library, University of California, San Diego, 9500 Gilman Drive, La Jolla, CA 92093-0175; clgoldman@ucsd.edu)   

Training librairans to be higher ups     
problems   
few new hires   
underqualified pools   
"Graying of profession"   
oranizational restructuring - flattening    
makes progression into management roles   

conducted study   
understand how succession planning is percevied/addressed by individ library deans   
methods  
case study - cross analysis design   

lit review - succession planning in librareis  - lack of literature abotu succession planning    

reseach questions about succession planning    

2 deans participated in studies   

dean internships were good    
advantages of flat organizational structures    

helps identify potential leaders   
direct observation discussion wiht librairans    

provide oppotunities for leadership experience    

Union contract inportance/difference for middle managers   


future research, exoand research to include more deans  
expand looking at additional academic hierarchies   

---


BREAK    


---

### hree Years After the Big Deal Cancellation: Examining the Data and Determining the Collection Development Implications, EMILY K. CHAN* and SUSAN L. KENDALL* (Dr. Martin Luther King, Jr. Library, San Jose State University, One Washington Square San Jose, CA 95192-0028; emily.chan@sjsu.edu; susan.kendall@sjsu.edu).


The big deal with Wiley    
vendor collections for purchasing for the CSU high prices caused cancellations 

recouped money and neee to find out what to do with it   

used funds to upgraded to EBSCO compelte as an alternative to dropping Wiley   

journal access is a moving target  
despite no subscription, wiley is stillw ell used.   
lots of turnaway titles    

will this create isseues with ILL?    





---

### Innovations in Open Science Achieved by Smart Publishing Choices, JULIA GELFAND (University of California, Irvine Libraries, Ayala Science Library 228, Irvine, CA 92612-9557; jgelfand@uci.edu).   



Open science   
best practices in schol comm   

lots of benefits of OA   
share ability and rights retention  

authors need to be aware:   
publishers can charge to publish OA content 


publishing - preprints are diffeernce than published works   

increase in predatory sources conferences, communications    

assessment functions   
metrics by output 

data and impact of research and scholarship    
opportunities for collaboration    
build support for science from Gov   
concerns    
global vs local   
what is innovation?    


what influences ar ethere in Open science   
open access policies - open data   
citizen sceince movement   

data management   
demand for research data to have a safety net for a long time    
encourage reuse     

responsibilities of Openess    






---



### Expanding The Library’s Reach and Redesigning Our Foundations, MARY LINN BERGSTROM1*, REID OTSUJI1*,KAREN HESKETT1, and TIM DENNIS2 (1University of California, San Diego, 9500 Gilman Dr #0699 La Jolla, CA 92093, mlbergstrom@ucsd.edu, rotsuji@ucsd.edu, kheskett@ucsd.edu; 2University of California, Los Angeles, 120S Election Walk, Los Angeles, CA 90095, timdennis@ucla.edu).




---


### Campus as a Living Lab: Using Your Library to Teach Sustainability! PEGGY CABRERA (San Jose State University, One Washington Square, San Jose, CA 95192-0028; peggy.cabrera@sjsu.edu).

teaching students sustainability    
IEQ 

Energy and atmosphere 
transportation and location 



---

### Outside of the Box Thinking: Inspiring Ways to Use Existing Library Technology to Create E-learning Objects, AMANDA ROTH (University of California, San Diego, Geisel Library, 9500 Gilman Drive, #0175Q, La Jolla, CA 92093-0175; a4roth@ucsd.edu).

e-learning objects - electronically 
used when face to face instruction isn't possible or ideal  
support for traditional instruction 

reusabel, scalable, shareable 

software tools, screen casting, rapid authoring  

object requirements:   
measurealble learning outcomes - that will take place during an instruction or event   
additinoal content -elearning object that is necessary to know but is outside of a learning outcome 

mode of delivery : 
objects delivered to learners   
known contraints  - known limitations or restrictions that affect the developmetn or delivery of the e-object  

feeback mechanizsms:   
in what wasy will you provide feedback to learners evaluate or assess the learning.  






---


### Library 101 Workshops: Emphasizing Basic Skills, PAUL HOTTINGER*, SALLY ROMERO*, JENNIFER BIDWELL*, and FREDA LIN* (California State Polytechnic University, Pomona, 3801 West Temple Avenue, Pomona, CA 91768, phottinger@cpp.edu, sallyromero@cpp.edu, jabidwell@cpp.edu, fwlin@cpp.edu).

library 101 series - 
Topics to tach 
library tour 
google searching 
finding articles using oneSearch & Google Scholar 

Finding & Locating books using oneSearch 
MLA citation 

APA Citation 

expanded topics from 6 -12  

workshop days Tues and thurs high attendence   






---












