---
title: "Iassist2018_notes"
author: "Reid Otsuji"
date: "5/30/2018"
output: html_document
---

# Iassist 2018 - Montreal  
## [Schedule](https://www.openconf.org/IASSIST2018/modules/request.php?module=oc_program&action=program.php)

## Day 1  
Keynote   

#### Plenary 1: Roberto Rocha (DB Clarke Auditorium, Hall Building)  
Abstract
Data Journalism: Dispatches from the Frontiers of Data Science and Storytelling

Data journalism is the marriage of social science and public-interest storytelling, using data as a source and employing reproducible analysis methods to arrive at a conclusion. This is a radical change from traditional ways of reporting, which often rely on anecdotes and paper documents. But despite being at its heart journalism, where crafting a gripping narrative is just as important as getting the facts right, data journalists haven't always been good at telling stories. This is changing, and we're entering a golden age of storytelling based on data and stats.

Biography
Roberto Rocha is a digital journalist and educator who specializes in data-driven reporting and storytelling. Mr. Rocha has worked with CBC Montreal since 2015, and formerly the Montreal Gazette from 2005 to 2015. He is a former lecturer of Advanced Digital Journalism at the University of Ottawa. More information can be found on Mr. Rocha’s website.
---

data storytellers
data journalism - 
data analysis for presentation - target audience for all 
need to present clear for everyone
e.g. looking at census data
developing narrative for data analysis and visualization 
uses data to find information about Canadians, e.g. analysis and viz kickstarter projects 

complex data - car sharing e.g. car to go 
mapping car 2 go data to see if parking cars take up residential spaces by car2go cars
exposed urban planning probs and transportation issues 

site created provides info for fatal encounters by police in canada 
created database victims by police 

ML example - buzzfeed US spy planes flying over cities - using public flight data records 

ProPublica - Machine bias project predicting reoffending criminals - data profiling black men. because of overrepresentation of data , e.g. watchdog technology 

data journalism - data analysis for developing stories 

computer assisted reporting - old term for data journalism
software improvements 
push for gov to release data - e.g. montreal open data advocacy groups portail donnees , quebec (open quebec) Open North gov data effort 

NICAR - nat. institute compute assisted reporting 

big graphics - make the user figure out the story 
communicate clearly and honestly - create the story 

e.g. jeff bezo banning powerpoints 
data scientists = storytellig

freytag's dramatic arch for storytelling 

e.g. pinellas county - tampa bay times
uses freytag arch for storytelling

state of gun violence video - use of data for storytelling youtube
make the reader a character in the story - e.g. uber driver example 

e.g. the globe and mail - police dismiss sexual assault claims - story written using data

NC jail inmates death poor supervision from jail
man gives out most parking tickets in boston - char study using data



# Road Maps for RDM Services, What Next?
#### Session Chair: Rachel Walton, Rollins College

### Scaling up RDM services at Duke University: Where we are now, what we have learned, and where we are going
#### Jennifer Darragh; Sophia Lafferty-Hess

looking at teams specifically for the repository development 
worked with liaison librarians - for presenting services to the greater community 

launched services in 2017 

RDM education: dev 12 unique workshops 
wroked with deam of academic affiars for grads - developed program all grads required to take 6 hours for credit 
challenge content cannot cover all disciplines
workshops e.g.
IRB
Research computing 

life cycle based services: based on environmental scanning
DMPs 
active project workflow management 
preservation and access services 

challenges:
distributed collaborative research - uses OSF for collaborative project solution 


repo services: 
moving to Fedora
preingest reveiw of data files 
streamlined deposit process - pre ingest process included 

what works:
DOis 
pre-publication review 
apply FAIR standards 
connections and collaborations with groups on campus e.g. events for DMP reviews DMPTool 
Data management education important - hearing about tools to use , challenge - don't know if practices are being followed 

marketing services continuously...

future processes:
increase marketing and outreach 

develop and offer discipline-specific wrokshops
DM fundamentals for Socsci, humanities, etc. - working with liaison libraians 
assessment of program - to see how effective marketing and services 



### CARL Portage: The RDM journey continues...
#### Jeff Moon; Shahira Khair; Lee Wilson
##### Expert groups available:
DMP
curation
data discovery
Preservation
Training
Research Intelligence

##### Working groups:
dataverse
Responsible reseearch data management practices for sensitive data

* issues with sensitive data:
how to mange sensitive data

* stakeholder engagement:
regional provincial - 4 library consortia

* Development of tri-agecy RDM infratstruce and policy:
what do institutions need - 
institutional strategy - providing guidnace
DMPs - uses DMP Assistant tool - moving to DMP Roadmap (DMPTool)
tri-agency policy will encourage DMP creation 


* Deposit:
partner with other institutions
Dataverse North
FRDR - DFDR data repositories 

##### Federated RDM Architecture: Repository 
* Active storage:  
Raw data, unprocessed data, cloud storoate, OSF - messy data   

* Repository storage - accessible  
dataverse, regional - Dalhousie & Abicus - examples of dataverses  
FRDR DFDR - used for large datasets "big data" creates bags and transfer with Globus - good resouce as a national repo  
instit. repos - e.g. Islandora, dryad, zonodo  
discipline repos - e.g. genbank  

use resources for storing data with metadata, sharing and accessibility 

storage layers:

* national discovery layer 
* Preservation processing (under development) - narmalization of files, open format conversions 
e.g. archivematica, Ontario library consortia 


future planning:
* distributed netowrk of curation support services 
* build tools and services for "active" data curation 
* implement geospatial discovery layer for end user
* create single end-user facing platform

---

### RDM roadmap to the future, Or, Lords and Ladies of the data
#### Robin Rice
serivce owner: data librarian
data curators & user support staff
software enginners 
compute infrastruc. staff

U of E 3 part [Roadmap](https://www.ed.ac.uk/is/rdm-roadmap) - living document 

implementing a Single unified RDM service:
* simplified data life cycle 
before research project, during project, after, training and support

1 service question to think about for unified RDM services: where do you draw the line between data and compute?

trying to build a mature single level of service: standarizing different parts of the services.  
focus/target on disciplines or domains as much as possible 

Services:  
DMP - key component for the service, get people thinking ahead of serivce uses ahead of time, work with school to make a DMP requirement as a part of the curriculum 
software management planning - how to manage software sustainablity e.g. reporducing data at a software level   

Working with data:
developing secure sensitive data, iso22001, using github and gitlab - currently using subversion, get reseachers to use ELNs DATA SAFE HAVEN 

Data stewardship options/goals:
enhancing display 0- including multimedia
Data vault - GDPR - secure long-term storage
embrace new tech and metadata standards for curating and providing access to research images 
communication about complexity of open and closed options  
FAIR repository development 

Training and support:   
need new communication plan document    
annoynimization training for sensitive data   
periodic GDPR training   

challenges:   
getting through workload   
managing stakeholders expectations   
keep up with field of RDM    
rearching beyond early adopters   
getting people to think abour FAIR    
Scholarly publishing competition vs Open    


---

### Implementing new data management and curation services at the University of Arizona (UA): Lessons learned from the UA data management and data curation pilot
#### Christine Kollen   
RDM services:  
training, develop RD ecosystem - integrating data, code, workflows, other scholarly artifacts 
Implementing FAIR practices   

Campus data management Advisory committee (2011)   

Libraries, ResearchIT, research office    

sent out a RMD survey - 375 respones, included asking intrest and willingness to pay for services   

Pilot funded by libraries, UITS, RDI, health sciences    

Pilots:   
Entomology - post-docs and students what did the need?    
Engineering education - moving data from excel to SQL database, document python script, and de-identifying data   
Wildlife Biology - file versioning, access and management protocols, managing student datases, sharing archived data  
Cancer research project - nih grant review, study closure and disposition, good DM practices   
Public Health - document and version control, document data workflow and data protocols    
  - recommended using Trello for file tracking   


RDM workshop bolstered researcher credibility with PIs    

Training recommentation:   
offer for-credit class in RDM - offer training and support services at new fac. orientation and beginning of grants  
good for service promotion   
training for liaisons    

user OSF for institutions   
data literacy workshop for post-docs, grads and fac   
best practices workshops for grad students, integrate into grad level courses in collaboration with liaisons    
provide training for liaisons   


only 2 people developing/scaling services    

New staff:   
RDM spec  
DS spec   
GIS spec  
Preservation Spec   
metadata spec   

---

###  After Lunch Session

---

# Improving Data Curation Workflows
#### Session Chair: Bobray Bordelon, Princeton University



### Caring for sharing: Improving self-deposit repository publishing systems
#### Anca Daniela Vlad

##### ReShare: Self desposit data service 
UK Data Service 
1305 collections - variety of disciplines 

online repo - archive pub and share data - self-deposit   
studies indexed using the HASSET 
metadata profile is DDI schema 
access controls customized for each collection   
files accepted zip or individual files  
top data ingested SocSci - psyc, econ, society   
top data types - qualitative and mixed methods & Experimental data   

##### ingest process:     
deposit pushed for review   
sent back for edits   
no edits, data is published and minted DOI   

Analytics tracked by Google Analytics 

user traffic/visits: search engines, URLs, social media via twitter   

tested mobile devices for viewing issues - very minimal usage   

##### Training:   
workshops, webinars, and drop-in sessions - primarily shows how to deposit into the system   
step-by step training: edit collections: data collections    

On going DM training   
Open access   
QAMYData - free tool/service that auto detects some of the most common problems in survey and other numeric data and creates "data health" check, PII, missing data, missing labels etc.  software auto checks items from initial review process    

---


### FORSbase: Implementing the fair principles for social science data archives
#### Stefan Buerli

what is FORS: nat. center of expertise for reserach in the soc sci in switzerland   
production of survey data  
consulting for researchers in switzerland    
DARIS FORS: research inventory 10900 project descriptions, 18800 researchers, 4500 institutions, 4760 active users   
data catalog 655 datasets - most have national importance   

development:    
needed services covering RDM life cycle of researh data   
simplified archiving and publishing    

FORSbase service:   
Research inventory   
data archive   
Survey tool   

Multilingual - french, german, english   
work environment for Socscientists 
metadata DDI   


Inventory & archive people:   
Researchers, FORS collaborator, researcher/consumer    

FORSbase2.0:   
Online access to all data in catalogue  
one stop shop   
online data deposit -  upload files and documentation while working on project   
receive auto feedback from system when data is being downloaded   
personal messaging system integration - sending private messages to contacts   
automated alerts and download of datasets e.g. request granting approval for use    
FORS Nessstar integratin for teaching   

#### Open data: 
FORSbase:    
FAIR Data principles -    
Made to measure soultion of data producers and users in relkation to FAIR principles and data protection laws    

FAIR principles applied:    
DOI assigned 
DDI metadata standards, CESSDA metadata standared 

Accessible:   
DOI, freely accessible, 
access requires vaild user account   
study metadata is persisitent    

Interopable:   
OAIS compliant   
DDI standard for desctiption    

Reuseable:   
Metadata related ot he nature of the data    
information related to dataset/project    


Future:   
modularity to make more generic open data repo SWISSUbase    

---


### Facilitating research data access – supporting data management and curation with community driven solutions
#### Wolfgang Zenk-Möltgen; Monika Linne; Jonas Recker

GESIS data archive for the social sciences   
Data sharing in the Social Sciences    
Roper center 1947 1st example of archiving data in Soc Sci    
GESIS founded in 1960s   
Data as "currency" - researchers data publications, research ords use data as assests that has to be managed.   
public admin collection stats data to provide "open gov data" for re-use   

challenges:   
more data is shared, in the long-tail   
citability expectations, accessibility, persistence fo data   
Data as research output:   
researchers, research orgs, funders, schol. journals commercial pubs,   

Training:    
more in RDM

more challenges:   
data sharing solutions e.g. FAIR principles   
data sharing for new data types and sensitive data   
linking of data and pub   

new services:  
da|ra for assignming DOIs   
datorium service addressing single researchers for self deposit and descript.    
replikationsserver:  
X-econ: address experimental data    
SowiDataNet project initiative:  addresses research organizations who want to manage their own data.   
service supports quality of documentation, data discovery and citation, persistence bitstream for 25 years, branding  

Tech: 
dspace 5.6   
PostfreSQL database   
OAI-PMH protocol   
DOIs da|ra service



### Optimizing data ingest: Experiences from ICPSR
#### Jared Lyle; Abay Israel; Justin Noble

metadata - finding the right balance and incentives to provide  

legal permisiions - do they have the authority to deposit content    
can you modify?   

ICPSR process - 2007 created online form    
simplify form - finding balance between information and length 
simplify steps to deposit -  lots of services make it a few steps to upload and describe data   

deposit workspace - went from form to workspace.  allows depositors to incrementally work on a submission as opposed to needing to upload and descripbe all files at once   

collaboration - users share projects with other collaborators and grant various permissions levels to these collaborators.  this allows for multiple researchers or PIs    

folder sturcture - projects needed flexibility to organize submissions in to folders    

file-level metadata - depositing materials.  researchers provide information 

project communication log - project log that allows for data depositor and ICPSR curators to send messages to each other.    

any file type can be imported/ingested.   

Deposit system improved other ICPSR tech.   
OpenICPSR, DataLumos - stored gov data for preservation, Census    
preview functionality on the study homepage    
help icons   
ICPSR metadata editor   

Internal and external feedback   
setup methods to receive user feedback, various audience and users   

---

## Afternoon session

---


## Putting the CURATE Model in Practice: Training for Data Curation [Panel]
#### Session Chair: Wendy Kozlowski, Cornell University

### Putting the CURATE model in practice: Training for data curation
#### Wendy Kozlowski; Jennifer Moore; Mara Blake

Wendy Kozlowski: Position in metadata services

campus wide research data management services group 
role of libraries in data curation 

libraries fit in in the long-tail of data 
libraries are good at instruction 

Data Curation Network Spec kit 354

scale data curation across all disciplines? 
data curation expertise:  
file format  
disciplines   

share curation staff across institutions:  DCN  

Curation training pilot   
awarded grant from IASSIST  
1 1/2 days introductory workshop   

curriculum:   
foundations of curation overview   
CURATE model training   
Panel presentations    
Student Project    

CURATE:   
checking files and metadata - files ope, code runs, metadata, docs  
understand  and run files- QA, hidden docs, doc for reuse   
request- missing info or changes  
augment- submissions with metadata   
transform- 
evaluate- rate the submission for FAIRness scorecard    

check list link in slides...    

training goals:   
define data curation , why it's needed, explorer library involvement   

Student project requirment:  
reflected on the curation activities learned and applied in the workshop   
2 things to do
expected challenges   
resources needed   
short-term goals   


E.g. check current datasets for FAIRness   

long-term impact   
gran project create intermediate to advanced lessons  


---


# Day 2

---

## Plenary 2: Dr. Stephanie Pyne (DB Clarke Auditorium, Hall Building)
#### Abstract
##### Cybercartography and Inclusion:  The Residential Schools Land Memory Mapping Project

Providing an inclusive space for many perspectives and encouraging people to express themselves in their own ways is a key ingredient of the kind of deliberative democracy envisioned in Inclusion and Democracy by Iris Marion Young, who recommended a broad approach to rationality that can accommodate alternative forms of communication such as greeting, rhetoric, and narrative.  Inclusion is also central to the critical cartographic view of the map as both a process and a narrative vehicle capable of reflecting multiple dimensions. The critical turn in cartography has led to a vast new range of possibilities for mediating reconciliation and social justice initiatives worldwide. Cybercartography is an evolving theoretical and practical framework for transdisciplinary collaborative projects to develop online interactive multimedia atlas websites intended to present multiple perspectives and dimensions of socioeconomic, political and cultural issues. Research began in 2007 on the prototype Cybercartographic Atlas of Indigenous Perspectives and Knowledge (Great Lakes-St. Lawrence Region), which provided the basis for the five-year SSHRC-funded Lake Huron Treaty Atlas Project (2009-2014), and in turn led to the current five-year SSHRC-funded Residential Schools Land Memory Mapping Project (RSLMMP, 2015-2020). This discussion tracks the evolution of the RSLMMP with a focus on inclusivity, emergence and the transdisciplinary research relationships that have developed through this evolution.

### Biography
Dr. Stephanie Pyne is a Post-Doctoral Fellow at the Carleton Geomatics and Cartographic Research Centre. A multidisciplinary researcher with policy experience working with the Justice Department, Dr. Pyne’s PhD work involved creating a cybercartographic atlas intended to shed light on the many dimensions of treaty relationships, including those under the Robinson Huron Treaty. In her current Post-Doctoral research assignment under the Residential Schools Land Memory Mapping Project (Social Sciences and Humanities Research Council of Canada Insight Grant, 2015-2020, PI, Dr. D.R. Fraser Taylor), she works with others in the Residential Schools reconciliation research and education community to expand the work undertaken in her doctoral and post-doctoral studies.

---

Cybercartography and inclusion: the residential schools land memory mapping project 

critical geography - concept of space interms of relationships 
critical cartography - performance emergence

mappings - expereince indiginous 

cybercartography - atlas narrative vehicles, place as organizing principles 

critical cartography - 
seven elements of cyber cartography  
multisensory   
uses multimedia formats   
highly interactive   
wide range of topics of intresest no just location finding    
not a stand alont project like traditional map    
compiled by teams of individuals from various disciplines   
involves new research partnershipa among academia, gove, civl society and private sector   


 e.g. websites cybercartographic atlases:   
 
showing weather/temps in various parts of antarctica   

Cybercartogaphic canada's trade with the world site   

pilot atlas of the risk of homeless site   

artic bay atlas   
 

GCRC carlton site : under Output link  - shows all the atlases   
GCRC site is an Atlas but looks like a website    

Thule Atlas  

New concetps and approaches:   
geo-transctiption  
mapping epiphany   
spatializing history   
tow-pronged and braided approach    
transdisciplnarity   
iterative processes    
reflexivity    


[lake huron traty atlas](http://lhta.ca)  

Survey Journeys Map Module   

---

# Session 1 - Day 2

## Professional Development in Data Services for Librarians
#### Session Chair: Amy Pienta, ICPSR, University of Michigan


## Building a bridge among experts: Data boot camp for East Asian studies librarians at the University of Michigan, United States
#### Jungwon Yang

2017 korean data workshop for east asian data service   

subject librairans needed to know about inst. repo and research data services   
building consultations accross units   
encourage conversations with faculty esp. in RDM service  
hire a data librarian for data consultation/management services   

need for data literacy ed. for regional experts    

korean data examples  
census population data   

positive feedback about workshop  

future planning text mining 




## Surveying the data liberators: The Canadian academic data landscape in 2017
#### Alexandra Cooper; Marilyn Andrews; Elizabeth Hill; Sandra Keys

Data Liberation Initiative  - DLI    
22 year old program   

Survey objectives:  
srvices materials needed   
training and ed   
satisfaction of services  
expertise   

overall repsonse rates  - 70%   

Data services question results   
teaching access/use data delivery tools high percentage 

Data services support popularity: 
dataverse  
spatial data  
data analysis  
Research Data center  
enhance metadata   
RDM  

RDM surveyed:   
48% has RDM services at libraries  
West canada had more   
RDM services are primarily in the library    
workshops/training  positive responses   
why people didn't attend training - proportion of data to entire job, level of complexity of training   

growth in GIS use - GIS is more interdisciplinary, possible reason for increase in use  
integration of GIS and data   
RDM front and center   


## Professional development of academic data librarians: A Canadian example
#### Elizabeth Hill; Siobhan Hanratty


Data Liberation Initiative  

Early data services in canada:
1963 at UBC  
1967 Carelton
1972 UWO 

data services found in social science centers   

Development of Training accross canada:
train the trainer and peer training   

training is essential for establishing a service   
peer led environment   

3 day training workshop 
content - identify gaps and knowledge skills   

4-5 regional training workshops   
IASSIST/CAPDU 2003   

traninig curriculum:
data services  
data management   
data structure   
data content   

early training focused on establishing and maintaining a data service   
survey of database content   
statistical literacy and practice   

Recent training focuses:
operating a data service - supporting  
survey and database content - census
Statistical literacy and practice - stats conecpts 
spceciliozed topics - mapping and viz, open data, RDM


less of a focus on using a computer and applications  

things still focused on   facing the feat 
mapping/GIS continues to group in popularity  
wide training options:   
in-person training - hands on   
DLI webinars   
training repo  
email lists  

DLI survival guilde


---

# Afternoon session  

---



## Open Data: Strategies for Sharing Government and Research Data
#### Session Chair: Lynda Kellam, University of North Carolina at Greensboro



### Where does Canada's social science research data live? An evaluation of data disposition [Paper included]
#### Peter Webster
Canadian research data repository inventory to locate where research data lives   
work to update Canadian data repos   
Sholar's portal, re3data, National research council of Canada 


23 SocSci related repos    
97 life sci  
71 natural sci  
11 engineering   
 

SocSci mostly Canadian universities, provincial government - Dataverse instances used for a good number   

E.g. data services  
BC Abacus  
Canada Health infoway   
Scholars portal list   
Portage   
SAGE Dataverse  
U. of Alberta Dataverse instance  

Other sources of Canadia reserach data:   
Portage federated research data repo FRDR
ICPSR - Statistics Canada data  
FAIRsharing.org   
Harvard Dataverse   
Medeley Data 

General data repo:  
Figshare  
Dryad  
Zenodo  


Elsivier: recommends ICPSR 
Springer Nature:  OpenICPSR, Harvard Dataverse, UK data service reShare, & OSF   

Taylor and Francis: dryad, figshare, zenodo, mendeley data, HD, 4tu.datacentrum, ANDS, and OSF 

WIley and Sage:  

More work needed to consolidate Canadian listing in re3data, fairsharing, portage FRDR  
Duplicate access needs to be reviewed 



## Enabling cross-search across social science data archives in Japan-initiative as part of national endeavor to establish open science infrastructure
#### Brian Mandikiana; Lois Timms-Ferrara; Marc Maynard; David Howell

japan several small socsci data archives (SSDA)  
not interconnected, not cross searchable, not connected organizationally   


risk data loss from being shutdown because of limited poeple support,  need to make archives finable and cross-searchable  
need to enhacve visibility domescitally and internat.   

RDM and open sci in japan:  
2015 promoting open sci in japan - cabinet office   

Open sci report similar to rest of the world,  open and acessible data requirements   


National institute in informatics  (NII) - provides 100gb backbone network, highspeed internat. lines between USA, EU, japan   
Scholarly information - journal articles, Catalog information, research information   

Services:  CiNii, JAIRO, CiNii books, 


808 institutional repos in japan   
 
reserach data infrastucture for Open sci:  Nii Open science platform  
working on various discovery, RDM, publication, metadata management platforms - beta version, with expectation of release in 2020  

various implementation options:  
IR layer - direct register to SS repo; transferred register to SS repo  
home-grown or DSpace storage system optioins  

discovery layer: 
3 options  
cross-ir discovery   
ss-specified disvoery   
single ssda discovery   

metadata schema:  
JAIRO cloud alows to use user-defined schema  
for harvesting uses junii2, similar to dublin core - junii2 will be upgraded to JPCOAR schema which is for research data not just publications   

DOIs:  
japan has specialized DOI services   


System configureations are tested thourgh pilot studies    
RUDA @ Rikkyo University     

issues:  
metadata schema   
how shoud the contents quality be standardized?  



## Data archiving for dissemination within a Gulf nation [Paper included]
#### Brian Mandikiana; Lois Timms-Ferrara; Marc Maynard; David Howell


SESRI - social and economic survey research institute  
established in 2008   
has collected over 60 nationally representatie house hold surveys   
eatch survey has 3 samples for each survey/  
conduction survey    

SESRI data archive eztablished in 2017   

SESRI has reserach units                                                                                                          
Dataq- ICS sharing in the Gulf, limit resource, comparative anyalsis 

archive needs final projuct  leag

leagal
working oh hirin addo..

student assists leff interetntd indd

  done by= dicnett tge rtioLL
  
  data center prtal   
  user and access support   
  promotion - marketing the archive conference and social media 
  
  clear comm with stake holders is the key   



## A tale of three data portals: Open government data in U.S. states
#### Bonnie Paige

opening data portals at state level of gov.  
3 case studies 
maine, new hapshire, vermont  

Portals:   
manie open gov data portal- dual portals, open checkbook for financial info   
uses socrative platform   

new hampshire 
lists of links to data related information   

Vermont:  
socrative based site, flexible category menu and feature data sets  
  
Vermont leads with most data sets also has the most active and passive use.  

New hapmsire data cannot be tract bcause of format, no information when contacted about sites.   
policies  -NH open data standards, Versmont


political influence in portable content 

what can we contribute to make it better?   
consisten metadata, data literarcy support e.g. how to use portals.   
better information architecture, correlation between city portal and state evlauation framework   
look at political influence accross states to see if the election has an influence   












